module.exports = [
	'I hate Russian dolls, they\'re so full of themselves.',
	'When I was younger I felt like a man trapped inside a woman’s body. Then I was born.',
	'Why did the bee get married? Because he found his honey.',
	'I recently decided to sell my vacuum cleaner as all it was doing was gathering dust.',
	'What would bears be without bees? Ears.',
	'Why don\'t lobsters give to charity? Because they\'re shellfish.',
	'I\'ve just written a song about tortillas; actually, it’s more of a rap.',
	'Why did the tomato blush? It saw the salad dressing!',
	'What do you call an almond in space? An astronut.',
	'I usually meet my girlfriend at 12:59 because I like that one-to-one time.',
	'People who jump off bridges in Paris are in Seine.',
	'I wondered why the baseball was getting bigger. Then it hit me.',
	'I couldn\'t quite remember how to throw a boomerang, but eventually, it came back to me.',
	'I recently got crushed by a pile of books, but I suppose I\'ve only got my shelf to blame.',
	'I\'d tell you a chemistry joke but I know I wouldn\'t get a reaction.',
	'I planned to find my watch today, but I didn\'t have the time.',
	'What do you call an alligator in a vest? Investigator.',
	'Why don\'t cannibals eat clowns. They taste rather funny.',
	'I couldn\'t work out how to fasten my seatbelt for ages. But then one day, it just clicked.',
	'Did you hear about the man who lost his entire left side in an accident? He\'s all right now.',
];
